version: 2.1
orbs:
  slack: circleci/slack@3.3.0
jobs:
  build:
    docker:
      - image: circleci/node:11-browsers-legacy
    working_directory: ~/$CIRCLE_PROJECT_REPONAME
    steps:
      - checkout:
          path: ~/$CIRCLE_PROJECT_REPONAME
      - slack/notify:
          title: Blavity News - blavity.com 
          title_link: 
          color: '#FFBD33'
          mentions: 'alfred'
          message: Changes are deploying to production for blavity.com
          webhook: https://hooks.slack.com/services/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
          author_name:

  deploy-docker-hub:
    docker:
      - image: circleci/node:11-browsers-legacy
    working_directory: ~/$CIRCLE_PROJECT_REPONAME
    steps:
      - checkout:
          path: ~/$CIRCLE_PROJECT_REPONAME
      - setup_remote_docker:
          version: 17.09.0-ce
          docker_layer_caching: true
      - run: |
          cd ~/$CIRCLE_PROJECT_REPONAME
          name=blavityinc/blavity.com:latest-prod
          docker build -t $name .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push $name
          echo "pushed $name"

  deploy-cloud-instance:
    docker:
      - image: gcr.io/google-appengine/nodejs
    working_directory: ~/$CIRCLE_PROJECT_REPONAME
    steps:
      - run: |
          mkdir /opt/blavity.com/
          echo $Google_Service_Key > /opt/blavity.com/gcloud-service-key.json
          export CLOUDSDK_CORE_DISABLE_PROMPTS=1 && curl -sSL https://sdk.cloud.google.com | bash
          source ~/google-cloud-sdk/completion.bash.inc
          source ~/google-cloud-sdk/path.bash.inc
          gcloud auth activate-service-account --key-file=/opt/blavity.com/gcloud-service-key.json
          gcloud --quiet config set project $Google_Project_ID
          gcloud beta compute instance-groups managed rolling-action replace blavity-ui-instance-group --region=us-east1 --max-surge=4 --max-unavailable=0 --min-ready 1m
          gcloud beta compute instance-groups managed rolling-action replace blavity-ui-instance-group-west --region=us-west2 --max-surge=3 --max-unavailable=0 --min-ready 1m
      - slack/notify:
          title: Blavity News - blavity.com 
          title_link: 
          color: '#FFBD33'
          mentions: 'alfred'
          message: Changes are deploying to production for blavity.com
          webhook: https://hooks.slack.com/services/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
          author_name:

workflows:
  version: 2
  workflow_build-only:
    jobs:
      - build
  workflow_build-deploy_docker_hub-restart_vms:
    jobs:
      - deploy-docker-hub:
          filters:
            branches:
              only:
                - master
      - deploy-cloud-instance:
          requires:
            - deploy-docker-hub
